services:
  app:
    init: true
    build: .
    container_name: apache2
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./apache-config:/etc/apache2
    environment:
      - APP_ENVIRONMENT_MODE=DEVELOPMENT
