services:
  app:
    init: true
    ports:
      - "80:80"
      - "443:443"
    container_name: apache2
    build: .
    volumes:
      - ./www:/var/www
      - ./config/apache2:/etc/apache2
      - ./config/php:/etc/php
  bundler:
    init: true
    container_name: bundler
    build: ./bundler
    volumes:
      - ./bundler/src:/bundler/src
      - ./www/html/css:/bundler/dist/css
      - ./www/html/js:/bundler/dist/js
      - ./www/html/fonts:/bundler/dist/fonts
