name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: >
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u
        "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Set up environment
      run: >
        echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV;
        REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2);
        echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

    - name: Build and run the bundler
      run: >
        docker build ./bundler -f bundler/Dockerfile.prod --tag
        ${{ secrets.DOCKERHUB_USERNAME }}/bundler:${{ env.IMAGE_TAG }};
        docker run --rm -v "$(pwd)/www/html/css:/bundler/dist/css"
        ${{ secrets.DOCKERHUB_USERNAME }}/bundler:${{ env.IMAGE_TAG }};

    - name: Build the Docker image with Dockerfile.prod
      run: >
        docker build . -f Dockerfile.prod --tag
        ${{ secrets.DOCKERHUB_USERNAME }}/$REPO_NAME:${{ env.IMAGE_TAG }}

    - name: Tag the Docker image as latest
      run: >
        docker tag
        ${{ secrets.DOCKERHUB_USERNAME }}/$REPO_NAME:${{ env.IMAGE_TAG }}
        ${{ secrets.DOCKERHUB_USERNAME }}/$REPO_NAME:latest

    - name: Push the Docker image with timestamp tag
      run: >
        docker push
        ${{ secrets.DOCKERHUB_USERNAME }}/$REPO_NAME:${{ env.IMAGE_TAG }}

    - name: Push the Docker image with latest tag
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/$REPO_NAME:latest
